#!/usr/bin/env python3
"""function examples for checking oin and language language"""

# 2 functions: check_pin, check_language
FUNC_EXAMPLES = [
    # check pin - 100 examples
    ("7979", "check_pin", {"pin": "7979"}),
    ("My PIN is 234", "check_pin", {"pin": "234"}),
    ("Four six seven nine", "check_pin", {"pin": "4679"}),
    ("Twelve eleven", "check_pin", {"pin": "1211"}),
    ("I think it's 6767", "check_pin", {"pin": "6767"}),
    ("PIN is zero six one eight", "check_pin", {"pin": "0618"}),

    # check pin - 100 examples (continued)
    ('ten-ten', 'check_pin', {'pin': '1010'}),
    ('Maybe one one one', 'check_pin', {'pin': '111'}),
    ('7 8 9', 'check_pin', {'pin': '789'}),
    ('8 um 0 8 0', 'check_pin', {'pin': '8080'}),
    ('Code is 0 0 4 5', 'check_pin', {'pin': '0045'}),
    ('It might be 777', 'check_pin', {'pin': '777'}),
    ('1010', 'check_pin', {'pin': '1010'}),
    ("I think it's 777", 'check_pin', {'pin': '777'}),
    ('Probably 999', 'check_pin', {'pin': '999'}),
    ('333', 'check_pin', {'pin': '333'}),
    ('sixty seven sixty seven', 'check_pin', {'pin': '6767'}),
    ('Code is 5 6 5 6 5', 'check_pin', {'pin': '56565'}),
    ('6 7 6 7', 'check_pin', {'pin': '6767'}),
    ('ten one zero', 'check_pin', {'pin': '1010'}),
    ('twelve one two one', 'check_pin', {'pin': '12121'}),
    ('one two one two one you know', 'check_pin', {'pin': '12121'}),
    ('777', 'check_pin', {'pin': '777'}),
    ('forty five four five', 'check_pin', {'pin': '4545'}),
    ('4545', 'check_pin', {'pin': '4545'}),
    ('111', 'check_pin', {'pin': '111'}),
    ('eight zero eight zero', 'check_pin', {'pin': '8080'}),
    ('The PIN is 1010', 'check_pin', {'pin': '1010'}),
    ('PIN is one two one two one', 'check_pin', {'pin': '12121'}),
    ('9 9 9', 'check_pin', {'pin': '999'}),
    ('PIN is 3 3 3', 'check_pin', {'pin': '333'}),
    ('4 5 4 5', 'check_pin', {'pin': '4545'}),
    ('Probably one two one two one', 'check_pin', {'pin': '12121'}),
    ('56565', 'check_pin', {'pin': '56565'}),
    ("I think it's four five four five", 'check_pin', {'pin': '4545'}),
    ("I believe it's 999", 'check_pin', {'pin': '999'}),
    ('My code is 333', 'check_pin', {'pin': '333'}),
    ('My code is 1 1 1', 'check_pin', {'pin': '111'}),
    ('The PIN is 6767', 'check_pin', {'pin': '6767'}),
    ("I believe it's 0 5 4 5", 'check_pin', {'pin': '0545'}),
    ('seven eight nine', 'check_pin', {'pin': '789'}),
    ('one oh one zero', 'check_pin', {'pin': '1010'}),
    ('PIN is 789', 'check_pin', {'pin': '789'}),
    ("I think it's 1 0 1 0", 'check_pin', {'pin': '1010'}),
    ('forty five-sixty four', 'check_pin', {'pin': '4564'}),
    ('three three three', 'check_pin', {'pin': '333'}),
    ('789', 'check_pin', {'pin': '789'}),
    ('six seven six seven', 'check_pin', {'pin': '6767'}),
    ('12121', 'check_pin', {'pin': '12121'}),
    ('5 6 5 6 5', 'check_pin', {'pin': '56565'}),
    ('Code is 12121', 'check_pin', {'pin': '12121'}),
    ('7 7 7', 'check_pin', {'pin': '777'}),
    ('1 0 1 0', 'check_pin', {'pin': '1010'}),
    ('Code is 7 8 9', 'check_pin', {'pin': '789'}),
    ('PIN is 6 7 6 7', 'check_pin', {'pin': '6767'}),
    ('Maybe six seven six seven', 'check_pin', {'pin': '6767'}),
    ('Probably 56565', 'check_pin', {'pin': '56565'}),
    ('five six five six five', 'check_pin', {'pin': '56565'}),
    ('you know 7 7 7', 'check_pin', {'pin': '777'}),
    ('The PIN is 111', 'check_pin', {'pin': '111'}),
    ('seven seven seven', 'check_pin', {'pin': '777'}),
    ('forty five forty five', 'check_pin', {'pin': '4545'}),
    ('Zero seven six seven', 'check_pin', {'pin': '0767'}),
    ('1 1 1', 'check_pin', {'pin': '111'}),
    ('PIN is 1 0 1 0', 'check_pin', {'pin': '1010'}),
    ('It might be 5 6 5 6 5', 'check_pin', {'pin': '56565'}),
    ('one one one', 'check_pin', {'pin': '111'}),
    ('eighty eight zero', 'check_pin', {'pin': '8080'}),
    ('The PIN is 56565', 'check_pin', {'pin': '56565'}),
    ('PIN is 8 0 8 0', 'check_pin', {'pin': '8080'}),
    ('ten ten', 'check_pin', {'pin': '1010'}),
    ('My PIN is four five four five', 'check_pin', {'pin': '4545'}),
    ("I think it's 333", 'check_pin', {'pin': '333'}),
    ("I believe it's one oh one zero", 'check_pin', {'pin': '1010'}),
    ('6767', 'check_pin', {'pin': '6767'}),
    ('Maybe 12121', 'check_pin', {'pin': '12121'}),
    ('fifty six five six five', 'check_pin', {'pin': '56565'}),
    ('8 0 8 0', 'check_pin', {'pin': '8080'}),
    ('My code is nine nine nine', 'check_pin', {'pin': '999'}),
    ('My PIN is seven seven seven', 'check_pin', {'pin': '777'}),
    ('eighty eighty', 'check_pin', {'pin': '8080'}),
    ("I think it's 8 0 8 0", 'check_pin', {'pin': '8080'}),
    ('eighty-eighty', 'check_pin', {'pin': '8080'}),
    ('Probably three three three', 'check_pin', {'pin': '333'}),
    ('one two one two one', 'check_pin', {'pin': '12121'}),
    ('um 111', 'check_pin', {'pin': '111'}),
    ('It might be seven eight nine', 'check_pin', {'pin': '789'}),
    ('8080', 'check_pin', {'pin': '8080'}),
    ("I think it's 6767", 'check_pin', {'pin': '6767'}),
    ('3 3 3', 'check_pin', {'pin': '333'}),
    ('1 2 1 2 1', 'check_pin', {'pin': '12121'}),
    ('My PIN is 8080', 'check_pin', {'pin': '8080'}),
    ('999', 'check_pin', {'pin': '999'}),
    ('four five four five', 'check_pin', {'pin': '4545'}),
    ('nine nine nine', 'check_pin', {'pin': '999'}),
    ('Code is seven seven seven', 'check_pin', {'pin': '777'}),
    ('sixty seven-sixty seven', 'check_pin', {'pin': '6767'}),
    ("I believe it's 8 0 8 0", 'check_pin', {'pin': '8080'}),
    ("I think it's 1 1 1", 'check_pin', {'pin': '111'}),
    ('Code is 999', 'check_pin', {'pin': '999'}),

    # check language - 100 examples
    ("I choose Spanish", "check_language", {"language": "Spanish"}),
    ("I want French", "check_language", {"language": "French"}),
    ("Spanish language", "check_language", {"language": "Spanish"}),
    ("Russian", "check_language", {"language": "Russian"}),
    ("German language, please", "check_language", {"language": "German"}),
    ("Haitian Creole", "check_language", {"language": "Haitian Creole"}),
    ("I need an interpreter for Hindi", "check_language", {"language": "Hindi"}),
    # check language - 100 examples (continued)
    ('please, I choose Xhosa', 'check_language', {'language': 'Xhosa'}),
    ('if you could, Danish language', 'check_language', {'language': 'Danish'}),
    ('Croatian language', 'check_language', {'language': 'Croatian'}),
    ('Croatian, thanks', 'check_language', {'language': 'Croatian'}),
    ('translation to Turkish', 'check_language', {'language': 'Turkish'}),
    ('Maybe Turkish?', 'check_language', {'language': 'Turkish'}),
    ('Give me Finnish', 'check_language', {'language': 'Finnish'}),
    ('Maybe Ukrainian?', 'check_language', {'language': 'Ukrainian'}),
    ('I need help in Finnish', 'check_language', {'language': 'Finnish'}),
    ('I want Croatian', 'check_language', {'language': 'Croatian'}),
    ('Can you do Croatian?', 'check_language', {'language': 'Croatian'}),
    ('Do you have Croatian?', 'check_language', {'language': 'Croatian'}),
    ('Can you do Turkish?', 'check_language', {'language': 'Turkish'}),
    ('Xhosa', 'check_language', {'language': 'Xhosa'}),
    ('if possible, Croatian language', 'check_language', {'language': 'Croatian'}),
    ('interpretation in Finnish', 'check_language', {'language': 'Finnish'}),
    ('I need help in Danish', 'check_language', {'language': 'Danish'}),
    ('Finnish please', 'check_language', {'language': 'Finnish'}),
    ('Xhosa would be great', 'check_language', {'language': 'Xhosa'}),
    ('Is Finnish available?', 'check_language', {'language': 'Finnish'}),
    ("Let's go with Danish", 'check_language', {'language': 'Danish'}),
    ('please, I select Danish', 'check_language', {'language': 'Danish'}),
    ('Xhosa language', 'check_language', {'language': 'Xhosa'}),
    ('if possible, I need Finnish', 'check_language', {'language': 'Finnish'}),
    ('I select Danish', 'check_language', {'language': 'Danish'}),
    ('Is Danish available?', 'check_language', {'language': 'Danish'}),
    ('Maybe Danish?', 'check_language', {'language': 'Danish'}),
    ('please, Finnish', 'check_language', {'language': 'Finnish'}),
    ('Do you have Finnish?', 'check_language', {'language': 'Finnish'}),
    ('a Danish interpreter', 'check_language', {'language': 'Danish'}),
    ('I need Danish', 'check_language', {'language': 'Danish'}),
    ('Can I have Xhosa', 'check_language', {'language': 'Xhosa'}),
    ('Ukrainian language', 'check_language', {'language': 'Ukrainian'}),
    ('Xhosa language, if possible', 'check_language', {'language': 'Xhosa'}),
    ('Finnish', 'check_language', {'language': 'Finnish'}),
    ('Danish would be great', 'check_language', {'language': 'Danish'}),
    ('a Ukrainian interpreter', 'check_language', {'language': 'Ukrainian'}),
    ('Ukrainian', 'check_language', {'language': 'Ukrainian'}),
    ('I need help in Xhosa', 'check_language', {'language': 'Xhosa'}),
    ('translation to Xhosa', 'check_language', {'language': 'Xhosa'}),
    ('Turkish', 'check_language', {'language': 'Turkish'}),
    ('I select Ukrainian', 'check_language', {'language': 'Ukrainian'}),
    ('I choose Turkish', 'check_language', {'language': 'Turkish'}),
    ('Give me Xhosa', 'check_language', {'language': 'Xhosa'}),
    ('Finnish language', 'check_language', {'language': 'Finnish'}),
    ('I want Finnish', 'check_language', {'language': 'Finnish'}),
    ('Give me Turkish', 'check_language', {'language': 'Turkish'}),
    ('a Xhosa interpreter', 'check_language', {'language': 'Xhosa'}),
    ('I need Finnish', 'check_language', {'language': 'Finnish'}),
    ('if possible, Ukrainian language', 'check_language', {'language': 'Ukrainian'}),
    ('Danish language', 'check_language', {'language': 'Danish'}),
    ('I want Croatian, thank you', 'check_language', {'language': 'Croatian'}),
    ('a Finnish interpreter', 'check_language', {'language': 'Finnish'}),
    ('I choose Ukrainian', 'check_language', {'language': 'Ukrainian'}),
    ('Can I have Danish', 'check_language', {'language': 'Danish'}),
    ('Finnish, thanks', 'check_language', {'language': 'Finnish'}),
    ('Turkish language', 'check_language', {'language': 'Turkish'}),
    ('I prefer Finnish', 'check_language', {'language': 'Finnish'}),
    ('I need Croatian', 'check_language', {'language': 'Croatian'}),
    ('Danish if you can', 'check_language', {'language': 'Danish'}),
    ('Is Xhosa available?', 'check_language', {'language': 'Xhosa'}),
    ('Croatian', 'check_language', {'language': 'Croatian'}),
    ('Turkish if you can', 'check_language', {'language': 'Turkish'}),
    ('I prefer Turkish', 'check_language', {'language': 'Turkish'}),
    ('I want Xhosa', 'check_language', {'language': 'Xhosa'}),
    ('Xhosa please', 'check_language', {'language': 'Xhosa'}),
    ("Let's go with Croatian", 'check_language', {'language': 'Croatian'}),
    ('Do you have Ukrainian?', 'check_language', {'language': 'Ukrainian'}),
    ('Is Croatian available?', 'check_language', {'language': 'Croatian'}),
    ('Danish', 'check_language', {'language': 'Danish'}),
    ('I choose Xhosa', 'check_language', {'language': 'Xhosa'}),
    ('Croatian if you can', 'check_language', {'language': 'Croatian'}),
    ('interpretation in Ukrainian', 'check_language', {'language': 'Ukrainian'}),
    ('a Croatian interpreter', 'check_language', {'language': 'Croatian'}),
    ('Turkish, thanks', 'check_language', {'language': 'Turkish'}),
    ('Maybe Xhosa?', 'check_language', {'language': 'Xhosa'}),
    ('Give me Ukrainian', 'check_language', {'language': 'Ukrainian'}),
    ('an interpreter for Danish', 'check_language', {'language': 'Danish'}),
    ('I need help in Croatian', 'check_language', {'language': 'Croatian'}),
    ('please, Turkish', 'check_language', {'language': 'Turkish'}),
    ('I choose Turkish, thank you', 'check_language', {'language': 'Turkish'}),
    ('interpretation in Turkish', 'check_language', {'language': 'Turkish'}),
    ('Danish, please', 'check_language', {'language': 'Danish'}),
    ('Do you have Turkish?', 'check_language', {'language': 'Turkish'}),
    ('Can I have Croatian', 'check_language', {'language': 'Croatian'}),
    ('thank you, I select Ukrainian', 'check_language', {'language': 'Ukrainian'}),
    ('an interpreter for Ukrainian', 'check_language', {'language': 'Ukrainian'}),
    ('Can you do Xhosa?', 'check_language', {'language': 'Xhosa'}),
    ('Maybe Finnish?', 'check_language', {'language': 'Finnish'}),
    ('I select Turkish', 'check_language', {'language': 'Turkish'}),
    ('an interpreter for Croatian', 'check_language', {'language': 'Croatian'}),
    ('I prefer Ukrainian', 'check_language', {'language': 'Ukrainian'}),
    ('a Turkish interpreter', 'check_language', {'language': 'Turkish'}),

    # check pin - 50 examples with irrelevant input
    ("Hello", "check_pin", {}),
    ("How are you?", "check_pin", {}),
    ("Let's talk", "check_pin", {}),
    ("My name is John", "check_pin", {}),
    ("Wait, what is this for?", "check_pin", {}),
    ("Hold on a sec", "check_pin", {}),
    ("Can you repeat that?", "check_pin", {}),
    ("I don't get it", "check_pin", {}),
    ("Why do you need that?", "check_pin", {}),
    ("Is this safe?", "check_pin", {}),
    ("I forgot what we were doing", "check_pin", {}),
    ("No thanks", "check_pin", {}),
    ("Not right now", "check_pin", {}),
    ("Maybe later", "check_pin", {}),
    ("Stop", "check_pin", {}),
    ("Cancel", "check_pin", {}),
    ("Back", "check_pin", {}),
    ("Go back", "check_pin", {}),
    ("Start over", "check_pin", {}),
    ("Help", "check_pin", {}),
    ("What can you do?", "check_pin", {}),
    ("Who are you?", "check_pin", {}),
    ("Are you a real person?", "check_pin", {}),
    ("This is taking forever", "check_pin", {}),
    ("Ugh", "check_pin", {}),
    ("lol", "check_pin", {}),
    ("brb", "check_pin", {}),
    ("Just checking", "check_pin", {}),
    ("I need to charge my phone", "check_pin", {}),
    ("My internet is acting up", "check_pin", {}),
    ("The app crashed", "check_pin", {}),
    ("It won't let me continue", "check_pin", {}),
    ("This screen is confusing", "check_pin", {}),
    ("Can I talk to support?", "check_pin", {}),
    ("Do you have a phone number?", "check_pin", {}),
    ("What's the price?", "check_pin", {}),
    ("Is it free?", "check_pin", {}),
    ("How long does it take?", "check_pin", {}),
    ("Where are you located?", "check_pin", {}),
    ("I moved recently", "check_pin", {}),
    ("My account is locked", "check_pin", {}),
    ("I can't log in", "check_pin", {}),
    ("I need to reset my password", "check_pin", {}),
    ("Send me a link", "check_pin", {}),
    ("Can you email me?", "check_pin", {}),
    ("I don't want to share personal info", "check_pin", {}),
    ("What time is it?", "check_pin", {}),
    ("Tell me a joke", "check_pin", {}),
    ("What's the weather like?", "check_pin", {}),

    # check language - 50 examples with irrelevant input
    ("Hello", "check_language", {}),
    ("How are you?", "check_language", {}),
    ("Let's talk", "check_language", {}),
    ("My name is John", "check_language", {}),
    ("Wait, what is this for?", "check_language", {}),
    ("Hold on a sec", "check_language", {}),
    ("Can you repeat that?", "check_language", {}),
    ("I don't get it", "check_language", {}),
    ("Why do you need that?", "check_language", {}),
    ("Is this safe?", "check_language", {}),
    ("I forgot what we were doing", "check_language", {}),
    ("No thanks", "check_language", {}),
    ("Not right now", "check_language", {}),
    ("Maybe later", "check_language", {}),
    ("Stop", "check_language", {}),
    ("Cancel", "check_language", {}),
    ("Back", "check_language", {}),
    ("Go back", "check_language", {}),
    ("Start over", "check_language", {}),
    ("Help", "check_language", {}),
    ("What can you do?", "check_language", {}),
    ("Who are you?", "check_language", {}),
    ("Are you a real person?", "check_language", {}),
    ("This is taking forever", "check_language", {}),
    ("Ugh", "check_language", {}),
    ("lol", "check_language", {}),
    ("brb", "check_language", {}),
    ("Just checking", "check_language", {}),
    ("I need to charge my phone", "check_language", {}),
    ("My internet is acting up", "check_language", {}),
    ("The app crashed", "check_language", {}),
    ("It won't let me continue", "check_language", {}),
    ("This screen is confusing", "check_language", {}),
    ("Can I talk to support?", "check_language", {}),
    ("Do you have a phone number?", "check_language", {}),
    ("What's the price?", "check_language", {}),
    ("Is it free?", "check_language", {}),
    ("How long does it take?", "check_language", {}),
    ("Where are you located?", "check_language", {}),
    ("I moved recently", "check_language", {}),
    ("My account is locked", "check_language", {}),
    ("I can't log in", "check_language", {}),
    ("I need to reset my password", "check_language", {}),
    ("Send me a link", "check_language", {}),
    ("Can you email me?", "check_language", {}),
    ("I don't want to share personal info", "check_language", {}),
    ("What time is it?", "check_language", {}),
    ("Tell me a joke", "check_language", {}),
    ("What's the weather like?", "check_language", {}),
]
